### ISSUE TITLE
Cant extract Wave Bank.xwb

### ISSUE THREAD

**Issue by mikuhl-dev** [trigger-death/TConvert#2]
I get this error: TypeInitializationException (The type initializer for 'TConvert.Extract.XactExtractor' threw an exception.)

**Comment by trigger-segfault** [comment]
I believe this may be caused by the Terraria Install Dir locator failing to find the directory. (The bug itself though is because I check for an empty string but not `null`).

I'll fix this issue but just to see if this is the real cause, is your Terraria installed in a non standard location?

**Comment by mikuhl-dev** [comment]
It is installed on my ssd, so yes not normal. But why would it need that for extracting?

**Comment by trigger-segfault** [comment]
It does not require it. Quick Wave Bank looks for `TrackList.txt` in a few places (included the Terraria install directory). This file is used to modify the track names that are listed to the left. Which is helpful if the game has updated with more tracks. The reason it crashed when failing to find it is my fault, not the fault of the user.

**Comment by trigger-segfault** [comment]
Alright, the hotfix has been released, you can download it [here](https://github.com/trigger-death/TConvert/releases/tag/1.0.2.1) or on the Terraria Forums thread. I'm pretty confident this was the issue, but please let me know if it works anyway. Thanks. :)

**Comment by mikuhl-dev** [comment]
I see. Does Terraria include a track list anyway? Couldn't find such a
thing except one of the files next to the sound bank had Track_1 to
Track_41 so I expected they just weren't named.

**Comment by trigger-segfault** [comment]
Terraria does not have a *named* track list. You can look up the track names in the database, but the best way to update them when the program itself isn't updated is to supply them yourself. It's also helpful if you want to edit an older version with different tracks.

**Comment by mikuhl-dev** [comment]
Works perfect thanks!

**Comment by trigger-segfault** [comment]
Awesome. Thanks for the quick replies to my questions! :)
